### ISSUE TITLE
Move to WinRM 1.3

### ISSUE THREAD

**Issue by carpnick** [chef/winrm-s#21]
Fix needed is the hard coded httptimeout of 60 minutes has been parameterized.  To get into knife-windows need this one updated first.

**Comment by adamedx** [comment]
@btm, this should go into knife-windows 1.0.0.

**Comment by carpnick** [comment]
Merged in from PR.  
Next step - when is the next WinRM-s release scheduled?

**Comment by btm** [comment]
@carpnick within a couple weeks. We'd like this to be included with a release candidate of knife-windows 1.0.0.

**Comment by carpnick** [comment]
@btm Thanks for the update.  Will adjust our plans accordingly.

**Comment by btm** [comment]
1.3.0.dev.0 was released on 2015-03-03 (4b47daf82826fff79135b454b8d5c0108d827f98) to allow testing against this. We've done some testing since then, and I think we've fixed bugs where necessary and pinned other gems to < 1.3 where necessary. I'm going to push 1.3.0 (final) right away.
