### ISSUE TITLE
Dealing With AllowUnencrypted

### ISSUE THREAD

**Issue by smurawski** [chef/winrm-s#26]
When Negotiate is selected and AllowUnencrypted is set to True on the remote node, we currently throw an error.  WinRS will succeed in this case.  As long as negotiate is supported on remote node, it will use that authentication mechanism.

At that stage, allowunencrypted controls whether or not the payload is being encrypted.  We should behave the same as winrs.  Otherwise, folks who want to use a higher level of security when possible (without SSL) but are in a mixed environment and want to retain some compatibility can use the negotiate on Windows and degrade to basic/plaintext on nix/Mac.

**Comment by btm** [comment]
@smurawski have you written any code for this yet or is this a fresh project?
